// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: risk_engine.proto

// Protobuf Java Version: 3.25.1
package com.titan.riskengine;

/**
 * Protobuf type {@code risk_engine.RiskCheckResponse}
 */
public final class RiskCheckResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:risk_engine.RiskCheckResponse)
    RiskCheckResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RiskCheckResponse.newBuilder() to construct.
  private RiskCheckResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RiskCheckResponse() {
    riskLevel_ = "";
    action_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RiskCheckResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.titan.riskengine.RiskEngineProto.internal_static_risk_engine_RiskCheckResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.titan.riskengine.RiskEngineProto.internal_static_risk_engine_RiskCheckResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.titan.riskengine.RiskCheckResponse.class, com.titan.riskengine.RiskCheckResponse.Builder.class);
  }

  public static final int RISK_SCORE_FIELD_NUMBER = 1;
  private int riskScore_ = 0;
  /**
   * <code>int32 risk_score = 1;</code>
   * @return The riskScore.
   */
  @java.lang.Override
  public int getRiskScore() {
    return riskScore_;
  }

  public static final int RISK_LEVEL_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object riskLevel_ = "";
  /**
   * <pre>
   * "LOW", "MEDIUM", "HIGH"
   * </pre>
   *
   * <code>string risk_level = 2;</code>
   * @return The riskLevel.
   */
  @java.lang.Override
  public java.lang.String getRiskLevel() {
    java.lang.Object ref = riskLevel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      riskLevel_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "LOW", "MEDIUM", "HIGH"
   * </pre>
   *
   * <code>string risk_level = 2;</code>
   * @return The bytes for riskLevel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRiskLevelBytes() {
    java.lang.Object ref = riskLevel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      riskLevel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTION_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object action_ = "";
  /**
   * <pre>
   * "ALLOW", "DENY", "MANUAL_REVIEW"
   * </pre>
   *
   * <code>string action = 3;</code>
   * @return The action.
   */
  @java.lang.Override
  public java.lang.String getAction() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      action_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "ALLOW", "DENY", "MANUAL_REVIEW"
   * </pre>
   *
   * <code>string action = 3;</code>
   * @return The bytes for action.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActionBytes() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      action_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (riskScore_ != 0) {
      output.writeInt32(1, riskScore_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(riskLevel_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, riskLevel_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, action_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (riskScore_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, riskScore_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(riskLevel_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, riskLevel_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, action_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.titan.riskengine.RiskCheckResponse)) {
      return super.equals(obj);
    }
    com.titan.riskengine.RiskCheckResponse other = (com.titan.riskengine.RiskCheckResponse) obj;

    if (getRiskScore()
        != other.getRiskScore()) return false;
    if (!getRiskLevel()
        .equals(other.getRiskLevel())) return false;
    if (!getAction()
        .equals(other.getAction())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RISK_SCORE_FIELD_NUMBER;
    hash = (53 * hash) + getRiskScore();
    hash = (37 * hash) + RISK_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getRiskLevel().hashCode();
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + getAction().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.titan.riskengine.RiskCheckResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.titan.riskengine.RiskCheckResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.titan.riskengine.RiskCheckResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.titan.riskengine.RiskCheckResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.titan.riskengine.RiskCheckResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.titan.riskengine.RiskCheckResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.titan.riskengine.RiskCheckResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.titan.riskengine.RiskCheckResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.titan.riskengine.RiskCheckResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.titan.riskengine.RiskCheckResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.titan.riskengine.RiskCheckResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.titan.riskengine.RiskCheckResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.titan.riskengine.RiskCheckResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code risk_engine.RiskCheckResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:risk_engine.RiskCheckResponse)
      com.titan.riskengine.RiskCheckResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.titan.riskengine.RiskEngineProto.internal_static_risk_engine_RiskCheckResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.titan.riskengine.RiskEngineProto.internal_static_risk_engine_RiskCheckResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.titan.riskengine.RiskCheckResponse.class, com.titan.riskengine.RiskCheckResponse.Builder.class);
    }

    // Construct using com.titan.riskengine.RiskCheckResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      riskScore_ = 0;
      riskLevel_ = "";
      action_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.titan.riskengine.RiskEngineProto.internal_static_risk_engine_RiskCheckResponse_descriptor;
    }

    @java.lang.Override
    public com.titan.riskengine.RiskCheckResponse getDefaultInstanceForType() {
      return com.titan.riskengine.RiskCheckResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.titan.riskengine.RiskCheckResponse build() {
      com.titan.riskengine.RiskCheckResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.titan.riskengine.RiskCheckResponse buildPartial() {
      com.titan.riskengine.RiskCheckResponse result = new com.titan.riskengine.RiskCheckResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.titan.riskengine.RiskCheckResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.riskScore_ = riskScore_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.riskLevel_ = riskLevel_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.action_ = action_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.titan.riskengine.RiskCheckResponse) {
        return mergeFrom((com.titan.riskengine.RiskCheckResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.titan.riskengine.RiskCheckResponse other) {
      if (other == com.titan.riskengine.RiskCheckResponse.getDefaultInstance()) return this;
      if (other.getRiskScore() != 0) {
        setRiskScore(other.getRiskScore());
      }
      if (!other.getRiskLevel().isEmpty()) {
        riskLevel_ = other.riskLevel_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getAction().isEmpty()) {
        action_ = other.action_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              riskScore_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              riskLevel_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              action_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int riskScore_ ;
    /**
     * <code>int32 risk_score = 1;</code>
     * @return The riskScore.
     */
    @java.lang.Override
    public int getRiskScore() {
      return riskScore_;
    }
    /**
     * <code>int32 risk_score = 1;</code>
     * @param value The riskScore to set.
     * @return This builder for chaining.
     */
    public Builder setRiskScore(int value) {

      riskScore_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 risk_score = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRiskScore() {
      bitField0_ = (bitField0_ & ~0x00000001);
      riskScore_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object riskLevel_ = "";
    /**
     * <pre>
     * "LOW", "MEDIUM", "HIGH"
     * </pre>
     *
     * <code>string risk_level = 2;</code>
     * @return The riskLevel.
     */
    public java.lang.String getRiskLevel() {
      java.lang.Object ref = riskLevel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        riskLevel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "LOW", "MEDIUM", "HIGH"
     * </pre>
     *
     * <code>string risk_level = 2;</code>
     * @return The bytes for riskLevel.
     */
    public com.google.protobuf.ByteString
        getRiskLevelBytes() {
      java.lang.Object ref = riskLevel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        riskLevel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "LOW", "MEDIUM", "HIGH"
     * </pre>
     *
     * <code>string risk_level = 2;</code>
     * @param value The riskLevel to set.
     * @return This builder for chaining.
     */
    public Builder setRiskLevel(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      riskLevel_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "LOW", "MEDIUM", "HIGH"
     * </pre>
     *
     * <code>string risk_level = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRiskLevel() {
      riskLevel_ = getDefaultInstance().getRiskLevel();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "LOW", "MEDIUM", "HIGH"
     * </pre>
     *
     * <code>string risk_level = 2;</code>
     * @param value The bytes for riskLevel to set.
     * @return This builder for chaining.
     */
    public Builder setRiskLevelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      riskLevel_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object action_ = "";
    /**
     * <pre>
     * "ALLOW", "DENY", "MANUAL_REVIEW"
     * </pre>
     *
     * <code>string action = 3;</code>
     * @return The action.
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "ALLOW", "DENY", "MANUAL_REVIEW"
     * </pre>
     *
     * <code>string action = 3;</code>
     * @return The bytes for action.
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "ALLOW", "DENY", "MANUAL_REVIEW"
     * </pre>
     *
     * <code>string action = 3;</code>
     * @param value The action to set.
     * @return This builder for chaining.
     */
    public Builder setAction(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      action_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "ALLOW", "DENY", "MANUAL_REVIEW"
     * </pre>
     *
     * <code>string action = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      action_ = getDefaultInstance().getAction();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "ALLOW", "DENY", "MANUAL_REVIEW"
     * </pre>
     *
     * <code>string action = 3;</code>
     * @param value The bytes for action to set.
     * @return This builder for chaining.
     */
    public Builder setActionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      action_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:risk_engine.RiskCheckResponse)
  }

  // @@protoc_insertion_point(class_scope:risk_engine.RiskCheckResponse)
  private static final com.titan.riskengine.RiskCheckResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.titan.riskengine.RiskCheckResponse();
  }

  public static com.titan.riskengine.RiskCheckResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RiskCheckResponse>
      PARSER = new com.google.protobuf.AbstractParser<RiskCheckResponse>() {
    @java.lang.Override
    public RiskCheckResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RiskCheckResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RiskCheckResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.titan.riskengine.RiskCheckResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

