// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: risk_engine.proto

// Protobuf Java Version: 3.25.1
package com.titan.riskengine;

public interface RiskCheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:risk_engine.RiskCheckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>double amount = 2;</code>
   * @return The amount.
   */
  double getAmount();
}
