// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: risk_engine.proto

// Protobuf Java Version: 3.25.1
package com.titan.riskengine;

public final class RiskEngineProto {
  private RiskEngineProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_risk_engine_RiskCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_risk_engine_RiskCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_risk_engine_RiskCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_risk_engine_RiskCheckResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021risk_engine.proto\022\013risk_engine\"3\n\020Risk" +
      "CheckRequest\022\017\n\007user_id\030\001 \001(\t\022\016\n\006amount\030" +
      "\002 \001(\001\"K\n\021RiskCheckResponse\022\022\n\nrisk_score" +
      "\030\001 \001(\005\022\022\n\nrisk_level\030\002 \001(\t\022\016\n\006action\030\003 \001" +
      "(\t2_\n\021RiskEngineService\022J\n\tCheckRisk\022\035.r" +
      "isk_engine.RiskCheckRequest\032\036.risk_engin" +
      "e.RiskCheckResponseB)\n\024com.titan.riskeng" +
      "ineB\017RiskEngineProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_risk_engine_RiskCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_risk_engine_RiskCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_risk_engine_RiskCheckRequest_descriptor,
        new java.lang.String[] { "UserId", "Amount", });
    internal_static_risk_engine_RiskCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_risk_engine_RiskCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_risk_engine_RiskCheckResponse_descriptor,
        new java.lang.String[] { "RiskScore", "RiskLevel", "Action", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
