// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: risk_engine.proto

// Protobuf Java Version: 3.25.1
package com.titan.riskengine;

public interface RiskCheckResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:risk_engine.RiskCheckResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 risk_score = 1;</code>
   * @return The riskScore.
   */
  int getRiskScore();

  /**
   * <pre>
   * "LOW", "MEDIUM", "HIGH"
   * </pre>
   *
   * <code>string risk_level = 2;</code>
   * @return The riskLevel.
   */
  java.lang.String getRiskLevel();
  /**
   * <pre>
   * "LOW", "MEDIUM", "HIGH"
   * </pre>
   *
   * <code>string risk_level = 2;</code>
   * @return The bytes for riskLevel.
   */
  com.google.protobuf.ByteString
      getRiskLevelBytes();

  /**
   * <pre>
   * "ALLOW", "DENY", "MANUAL_REVIEW"
   * </pre>
   *
   * <code>string action = 3;</code>
   * @return The action.
   */
  java.lang.String getAction();
  /**
   * <pre>
   * "ALLOW", "DENY", "MANUAL_REVIEW"
   * </pre>
   *
   * <code>string action = 3;</code>
   * @return The bytes for action.
   */
  com.google.protobuf.ByteString
      getActionBytes();
}
