// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: engagement.proto

// Protobuf Java Version: 3.25.1
package com.titan.notifications.grpc;

public final class EngagementProto {
  private EngagementProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EngagementRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:titan.ai.EngagementRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string user_id = 1;</code>
     * @return The userId.
     */
    java.lang.String getUserId();
    /**
     * <code>string user_id = 1;</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>string notification_type = 2;</code>
     * @return The notificationType.
     */
    java.lang.String getNotificationType();
    /**
     * <code>string notification_type = 2;</code>
     * @return The bytes for notificationType.
     */
    com.google.protobuf.ByteString
        getNotificationTypeBytes();
  }
  /**
   * Protobuf type {@code titan.ai.EngagementRequest}
   */
  public static final class EngagementRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:titan.ai.EngagementRequest)
      EngagementRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EngagementRequest.newBuilder() to construct.
    private EngagementRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EngagementRequest() {
      userId_ = "";
      notificationType_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EngagementRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.titan.notifications.grpc.EngagementProto.internal_static_titan_ai_EngagementRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.titan.notifications.grpc.EngagementProto.internal_static_titan_ai_EngagementRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.titan.notifications.grpc.EngagementProto.EngagementRequest.class, com.titan.notifications.grpc.EngagementProto.EngagementRequest.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object userId_ = "";
    /**
     * <code>string user_id = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string user_id = 1;</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOTIFICATION_TYPE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object notificationType_ = "";
    /**
     * <code>string notification_type = 2;</code>
     * @return The notificationType.
     */
    @java.lang.Override
    public java.lang.String getNotificationType() {
      java.lang.Object ref = notificationType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        notificationType_ = s;
        return s;
      }
    }
    /**
     * <code>string notification_type = 2;</code>
     * @return The bytes for notificationType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNotificationTypeBytes() {
      java.lang.Object ref = notificationType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notificationType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(notificationType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, notificationType_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(notificationType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, notificationType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.titan.notifications.grpc.EngagementProto.EngagementRequest)) {
        return super.equals(obj);
      }
      com.titan.notifications.grpc.EngagementProto.EngagementRequest other = (com.titan.notifications.grpc.EngagementProto.EngagementRequest) obj;

      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (!getNotificationType()
          .equals(other.getNotificationType())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + NOTIFICATION_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getNotificationType().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.titan.notifications.grpc.EngagementProto.EngagementRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.titan.notifications.grpc.EngagementProto.EngagementRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.titan.notifications.grpc.EngagementProto.EngagementRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.titan.notifications.grpc.EngagementProto.EngagementRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.titan.notifications.grpc.EngagementProto.EngagementRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.titan.notifications.grpc.EngagementProto.EngagementRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.titan.notifications.grpc.EngagementProto.EngagementRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.titan.notifications.grpc.EngagementProto.EngagementRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.titan.notifications.grpc.EngagementProto.EngagementRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.titan.notifications.grpc.EngagementProto.EngagementRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.titan.notifications.grpc.EngagementProto.EngagementRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.titan.notifications.grpc.EngagementProto.EngagementRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.titan.notifications.grpc.EngagementProto.EngagementRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code titan.ai.EngagementRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:titan.ai.EngagementRequest)
        com.titan.notifications.grpc.EngagementProto.EngagementRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.titan.notifications.grpc.EngagementProto.internal_static_titan_ai_EngagementRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.titan.notifications.grpc.EngagementProto.internal_static_titan_ai_EngagementRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.titan.notifications.grpc.EngagementProto.EngagementRequest.class, com.titan.notifications.grpc.EngagementProto.EngagementRequest.Builder.class);
      }

      // Construct using com.titan.notifications.grpc.EngagementProto.EngagementRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        userId_ = "";
        notificationType_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.titan.notifications.grpc.EngagementProto.internal_static_titan_ai_EngagementRequest_descriptor;
      }

      @java.lang.Override
      public com.titan.notifications.grpc.EngagementProto.EngagementRequest getDefaultInstanceForType() {
        return com.titan.notifications.grpc.EngagementProto.EngagementRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.titan.notifications.grpc.EngagementProto.EngagementRequest build() {
        com.titan.notifications.grpc.EngagementProto.EngagementRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.titan.notifications.grpc.EngagementProto.EngagementRequest buildPartial() {
        com.titan.notifications.grpc.EngagementProto.EngagementRequest result = new com.titan.notifications.grpc.EngagementProto.EngagementRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.titan.notifications.grpc.EngagementProto.EngagementRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.notificationType_ = notificationType_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.titan.notifications.grpc.EngagementProto.EngagementRequest) {
          return mergeFrom((com.titan.notifications.grpc.EngagementProto.EngagementRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.titan.notifications.grpc.EngagementProto.EngagementRequest other) {
        if (other == com.titan.notifications.grpc.EngagementProto.EngagementRequest.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getNotificationType().isEmpty()) {
          notificationType_ = other.notificationType_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                userId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                notificationType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object userId_ = "";
      /**
       * <code>string user_id = 1;</code>
       * @return The userId.
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_id = 1;</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_id = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        userId_ = getDefaultInstance().getUserId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 1;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object notificationType_ = "";
      /**
       * <code>string notification_type = 2;</code>
       * @return The notificationType.
       */
      public java.lang.String getNotificationType() {
        java.lang.Object ref = notificationType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          notificationType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string notification_type = 2;</code>
       * @return The bytes for notificationType.
       */
      public com.google.protobuf.ByteString
          getNotificationTypeBytes() {
        java.lang.Object ref = notificationType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          notificationType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string notification_type = 2;</code>
       * @param value The notificationType to set.
       * @return This builder for chaining.
       */
      public Builder setNotificationType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        notificationType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string notification_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNotificationType() {
        notificationType_ = getDefaultInstance().getNotificationType();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string notification_type = 2;</code>
       * @param value The bytes for notificationType to set.
       * @return This builder for chaining.
       */
      public Builder setNotificationTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        notificationType_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:titan.ai.EngagementRequest)
    }

    // @@protoc_insertion_point(class_scope:titan.ai.EngagementRequest)
    private static final com.titan.notifications.grpc.EngagementProto.EngagementRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.titan.notifications.grpc.EngagementProto.EngagementRequest();
    }

    public static com.titan.notifications.grpc.EngagementProto.EngagementRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EngagementRequest>
        PARSER = new com.google.protobuf.AbstractParser<EngagementRequest>() {
      @java.lang.Override
      public EngagementRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EngagementRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EngagementRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.titan.notifications.grpc.EngagementProto.EngagementRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EngagementResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:titan.ai.EngagementResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 optimal_timestamp = 1;</code>
     * @return The optimalTimestamp.
     */
    long getOptimalTimestamp();

    /**
     * <code>double confidence_score = 2;</code>
     * @return The confidenceScore.
     */
    double getConfidenceScore();

    /**
     * <code>bool send_immediately = 3;</code>
     * @return The sendImmediately.
     */
    boolean getSendImmediately();
  }
  /**
   * Protobuf type {@code titan.ai.EngagementResponse}
   */
  public static final class EngagementResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:titan.ai.EngagementResponse)
      EngagementResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EngagementResponse.newBuilder() to construct.
    private EngagementResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EngagementResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EngagementResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.titan.notifications.grpc.EngagementProto.internal_static_titan_ai_EngagementResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.titan.notifications.grpc.EngagementProto.internal_static_titan_ai_EngagementResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.titan.notifications.grpc.EngagementProto.EngagementResponse.class, com.titan.notifications.grpc.EngagementProto.EngagementResponse.Builder.class);
    }

    public static final int OPTIMAL_TIMESTAMP_FIELD_NUMBER = 1;
    private long optimalTimestamp_ = 0L;
    /**
     * <code>int64 optimal_timestamp = 1;</code>
     * @return The optimalTimestamp.
     */
    @java.lang.Override
    public long getOptimalTimestamp() {
      return optimalTimestamp_;
    }

    public static final int CONFIDENCE_SCORE_FIELD_NUMBER = 2;
    private double confidenceScore_ = 0D;
    /**
     * <code>double confidence_score = 2;</code>
     * @return The confidenceScore.
     */
    @java.lang.Override
    public double getConfidenceScore() {
      return confidenceScore_;
    }

    public static final int SEND_IMMEDIATELY_FIELD_NUMBER = 3;
    private boolean sendImmediately_ = false;
    /**
     * <code>bool send_immediately = 3;</code>
     * @return The sendImmediately.
     */
    @java.lang.Override
    public boolean getSendImmediately() {
      return sendImmediately_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (optimalTimestamp_ != 0L) {
        output.writeInt64(1, optimalTimestamp_);
      }
      if (java.lang.Double.doubleToRawLongBits(confidenceScore_) != 0) {
        output.writeDouble(2, confidenceScore_);
      }
      if (sendImmediately_ != false) {
        output.writeBool(3, sendImmediately_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (optimalTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, optimalTimestamp_);
      }
      if (java.lang.Double.doubleToRawLongBits(confidenceScore_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, confidenceScore_);
      }
      if (sendImmediately_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, sendImmediately_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.titan.notifications.grpc.EngagementProto.EngagementResponse)) {
        return super.equals(obj);
      }
      com.titan.notifications.grpc.EngagementProto.EngagementResponse other = (com.titan.notifications.grpc.EngagementProto.EngagementResponse) obj;

      if (getOptimalTimestamp()
          != other.getOptimalTimestamp()) return false;
      if (java.lang.Double.doubleToLongBits(getConfidenceScore())
          != java.lang.Double.doubleToLongBits(
              other.getConfidenceScore())) return false;
      if (getSendImmediately()
          != other.getSendImmediately()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPTIMAL_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOptimalTimestamp());
      hash = (37 * hash) + CONFIDENCE_SCORE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getConfidenceScore()));
      hash = (37 * hash) + SEND_IMMEDIATELY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSendImmediately());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.titan.notifications.grpc.EngagementProto.EngagementResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.titan.notifications.grpc.EngagementProto.EngagementResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.titan.notifications.grpc.EngagementProto.EngagementResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.titan.notifications.grpc.EngagementProto.EngagementResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.titan.notifications.grpc.EngagementProto.EngagementResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.titan.notifications.grpc.EngagementProto.EngagementResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.titan.notifications.grpc.EngagementProto.EngagementResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.titan.notifications.grpc.EngagementProto.EngagementResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.titan.notifications.grpc.EngagementProto.EngagementResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.titan.notifications.grpc.EngagementProto.EngagementResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.titan.notifications.grpc.EngagementProto.EngagementResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.titan.notifications.grpc.EngagementProto.EngagementResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.titan.notifications.grpc.EngagementProto.EngagementResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code titan.ai.EngagementResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:titan.ai.EngagementResponse)
        com.titan.notifications.grpc.EngagementProto.EngagementResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.titan.notifications.grpc.EngagementProto.internal_static_titan_ai_EngagementResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.titan.notifications.grpc.EngagementProto.internal_static_titan_ai_EngagementResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.titan.notifications.grpc.EngagementProto.EngagementResponse.class, com.titan.notifications.grpc.EngagementProto.EngagementResponse.Builder.class);
      }

      // Construct using com.titan.notifications.grpc.EngagementProto.EngagementResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        optimalTimestamp_ = 0L;
        confidenceScore_ = 0D;
        sendImmediately_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.titan.notifications.grpc.EngagementProto.internal_static_titan_ai_EngagementResponse_descriptor;
      }

      @java.lang.Override
      public com.titan.notifications.grpc.EngagementProto.EngagementResponse getDefaultInstanceForType() {
        return com.titan.notifications.grpc.EngagementProto.EngagementResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.titan.notifications.grpc.EngagementProto.EngagementResponse build() {
        com.titan.notifications.grpc.EngagementProto.EngagementResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.titan.notifications.grpc.EngagementProto.EngagementResponse buildPartial() {
        com.titan.notifications.grpc.EngagementProto.EngagementResponse result = new com.titan.notifications.grpc.EngagementProto.EngagementResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.titan.notifications.grpc.EngagementProto.EngagementResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.optimalTimestamp_ = optimalTimestamp_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.confidenceScore_ = confidenceScore_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.sendImmediately_ = sendImmediately_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.titan.notifications.grpc.EngagementProto.EngagementResponse) {
          return mergeFrom((com.titan.notifications.grpc.EngagementProto.EngagementResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.titan.notifications.grpc.EngagementProto.EngagementResponse other) {
        if (other == com.titan.notifications.grpc.EngagementProto.EngagementResponse.getDefaultInstance()) return this;
        if (other.getOptimalTimestamp() != 0L) {
          setOptimalTimestamp(other.getOptimalTimestamp());
        }
        if (other.getConfidenceScore() != 0D) {
          setConfidenceScore(other.getConfidenceScore());
        }
        if (other.getSendImmediately() != false) {
          setSendImmediately(other.getSendImmediately());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                optimalTimestamp_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 17: {
                confidenceScore_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 24: {
                sendImmediately_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long optimalTimestamp_ ;
      /**
       * <code>int64 optimal_timestamp = 1;</code>
       * @return The optimalTimestamp.
       */
      @java.lang.Override
      public long getOptimalTimestamp() {
        return optimalTimestamp_;
      }
      /**
       * <code>int64 optimal_timestamp = 1;</code>
       * @param value The optimalTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setOptimalTimestamp(long value) {

        optimalTimestamp_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 optimal_timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOptimalTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        optimalTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private double confidenceScore_ ;
      /**
       * <code>double confidence_score = 2;</code>
       * @return The confidenceScore.
       */
      @java.lang.Override
      public double getConfidenceScore() {
        return confidenceScore_;
      }
      /**
       * <code>double confidence_score = 2;</code>
       * @param value The confidenceScore to set.
       * @return This builder for chaining.
       */
      public Builder setConfidenceScore(double value) {

        confidenceScore_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double confidence_score = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearConfidenceScore() {
        bitField0_ = (bitField0_ & ~0x00000002);
        confidenceScore_ = 0D;
        onChanged();
        return this;
      }

      private boolean sendImmediately_ ;
      /**
       * <code>bool send_immediately = 3;</code>
       * @return The sendImmediately.
       */
      @java.lang.Override
      public boolean getSendImmediately() {
        return sendImmediately_;
      }
      /**
       * <code>bool send_immediately = 3;</code>
       * @param value The sendImmediately to set.
       * @return This builder for chaining.
       */
      public Builder setSendImmediately(boolean value) {

        sendImmediately_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool send_immediately = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendImmediately() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sendImmediately_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:titan.ai.EngagementResponse)
    }

    // @@protoc_insertion_point(class_scope:titan.ai.EngagementResponse)
    private static final com.titan.notifications.grpc.EngagementProto.EngagementResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.titan.notifications.grpc.EngagementProto.EngagementResponse();
    }

    public static com.titan.notifications.grpc.EngagementProto.EngagementResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EngagementResponse>
        PARSER = new com.google.protobuf.AbstractParser<EngagementResponse>() {
      @java.lang.Override
      public EngagementResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EngagementResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EngagementResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.titan.notifications.grpc.EngagementProto.EngagementResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_titan_ai_EngagementRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_titan_ai_EngagementRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_titan_ai_EngagementResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_titan_ai_EngagementResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020engagement.proto\022\010titan.ai\"?\n\021Engageme" +
      "ntRequest\022\017\n\007user_id\030\001 \001(\t\022\031\n\021notificati" +
      "on_type\030\002 \001(\t\"c\n\022EngagementResponse\022\031\n\021o" +
      "ptimal_timestamp\030\001 \001(\003\022\030\n\020confidence_sco" +
      "re\030\002 \001(\001\022\030\n\020send_immediately\030\003 \001(\0102h\n\021En" +
      "gagementService\022S\n\026GetOptimalDeliveryTim" +
      "e\022\033.titan.ai.EngagementRequest\032\034.titan.a" +
      "i.EngagementResponseB/\n\034com.titan.notifi" +
      "cations.grpcB\017EngagementProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_titan_ai_EngagementRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_titan_ai_EngagementRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_titan_ai_EngagementRequest_descriptor,
        new java.lang.String[] { "UserId", "NotificationType", });
    internal_static_titan_ai_EngagementResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_titan_ai_EngagementResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_titan_ai_EngagementResponse_descriptor,
        new java.lang.String[] { "OptimalTimestamp", "ConfidenceScore", "SendImmediately", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
